import Head from 'next/head'
import React from 'react'

const FlightDetail = () => {
  return (
    <div>
      <Head>
        <title>Traveling Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </div>
  )
}

export default FlightDetail
