import Head from 'next/head'
import React, { useState } from 'react'
import userLayout from '../../layouts/userLayout'
import HotelHero from '../../components/hero/hotelHero'
import TravelPrice from '../../components/travelPrice'
import LocationAbout from '../../components/locationAbout'
import TravelList from '../../components/travelList'
import firstPhoto from "../../public/images/firstsearch.png"
import secondPhoto from "../../public/images/secondsearch.png"
import thirdPhoto from "../../public/images/thirdsearch.png"
import fourthPhoto from "../../public/images/fourthsearch.png"


const Hotel = () => {
  const [datas, setDatas] = useState([
    {
      title: "Istanbul, Turkey",
      skills: ["Flights", "Hotels", "Resorts"],
      img: firstPhoto,
    },
    {
      title: "Sydney, Australia",
      skills: ["Flights", "Hotels", "Resorts"],
      img: secondPhoto,
    },
    {
      title: "Baku, Azerbaijan",
      skills: ["Flights", "Hotels", "Resorts"],
      img: thirdPhoto,
    },
    {
      title: "Malé, Maldives",
      skills: ["Flights", "Hotels", "Resorts"],
      img: fourthPhoto,
    },
  ]);
  return (
    <div>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HotelHero/>
      <TravelList datas={datas}/>
      <TravelPrice/>
      <LocationAbout/>
    </div>
  )
}

export default Hotel
Hotel.layout = userLayout