import Head from 'next/head'
import React from 'react'
import userLayout from '../../layouts/userLayout'

const HotelList = () => {
  return (
    <div>
       <Head>
        <title>Hotel List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </div>
  )
}

export default HotelList
HotelList.layout = userLayout