import React, { useState } from 'react'
import Head from 'next/head'
import HomeLayout from '../layouts/homeLayout'
import Hero from '../components/hero'
import TravelList from '../components/travelList'
import Reviews from '../components/reviews'
import firstPhoto from "../public/images/Columbia.png"
import secondPhoto from "../public/images/Melbourne.png"
import thirdPhoto from "../public/images/London.png"
import fourthPhoto from "../public/images/Paris.png"
import Image from 'next/image'
import { BsSendFill } from 'react-icons/bs'
import flight from "../public/images/flight-landing.png"
import hotel from "../public/images/hotel-landing.png"

const Home = () => {
  const [datas, setDatas] = useState([
    {
      title: "Istanbul, Turkey",
      skills: ["Flights", "Hotels", "Resorts"],
      img: firstPhoto,
    },
    {
      title: "Sydney, Australia",
      skills: ["Flights", "Hotels", "Resorts"],
      img: secondPhoto,
    },
    {
      title: "Baku, Azerbaijan",
      skills: ["Flights", "Hotels", "Resorts"],
      img: thirdPhoto,
    },
    {
      title: "Malé, Maldives",
      skills: ["Flights", "Hotels", "Resorts"],
      img: fourthPhoto,
    },
  ]);

  const [pages, setPages] = useState([
    {
      title: "Flights",
      desc: "Search Flights & Places Hire to our most popular destinations",
      img: flight,
      btnText: (
        <span className="flex items-center gap-1">
          <BsSendFill />
          Show Filghts
        </span>
      ),
    },
    {
      title: "Hotels",
      desc: "Search hotels & Places Hire to our most popular destinations",
      img: hotel,
      btnText: (
        <span className="flex items-center gap-1">
          <BsSendFill />
          Show Hotels
        </span>
      ),
    },
  ]);

  return (
    <div className='myContainer'>
      <Head>
        <title>Traveling Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <TravelList datas={datas}/>
      <div className="grid grid-cols-12 gap-6 mt-16">
        {pages?.map((item, index) => (
          <div className="md:col-span-6 col-span-12 relative " key={index}>
            <Image src={item?.img} className="object-cover" alt="" />
            <div className="absolute bottom-0 left-0 right-0 z-10 flex flex-col items-center p-6 rounded-bl-[20px] rounded-br-[20px] shadow-img">
              <h3 className="text-[40px] font-bold text-white font-TradeGothic">
                {item?.title}
              </h3>
              <p className="text-base font-Montserrat text-white max-w-[400px] text-center">
                {item?.desc}
              </p>
              <button className="px-4 py-4 bg-[#8dd3bb] rounded-[4px] mt-4 ">
                {item?.btnText}
              </button>
            </div>
          </div>
        ))}
      </div>
      <Reviews/>
    </div>
  )
}

export default Home
Home.layout = HomeLayout