import Head from "next/head";
import userLayout from "../layouts/userLayout";
import Hero from "../components/hero";
import Map from "../components/map";
import TravelPrice from "../components/travelPrice";
import LocationAbout from "../components/locationAbout";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Traveling Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Map />
      <TravelPrice />
      <LocationAbout/>
    </div>
  );
}
Home.layout = userLayout;
